#############################
# zxfs (zero x file system) #
#############################

#
#	util/mkzx/Makefile
#
#	Copyright (c) 2013 cg011235 <cg011235@gmail.com>
#
#	Make file for mkzx program
#

CC=gcc
CCFLAGS=#'-Wall'
LDFLAGS=
SOURCES='mkzx.c'
EXECUTABLE='mkzx'	

all:
	${CC} ${CCFLAGS} ${LDFLAGS} ${SOURCES} -o ${EXECUTABLE}

clean:
	rm -f ${EXECUTABLE}
